config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :todos do
    member do
      patch :complete
    end
  end

  patch 'complete', to: 'todos#complete'

  root 'todos#index'

  namespace :user do
    get 'todos/index' => 'todos#index'
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /todos
  def index
    @todos = current_user.todos.order(:done).all
  end

  # GET /todos/1
  def show
  end

  # GET /todos/new
  def new
    @todo = current_user.todos.build
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  def create
    @todo = current_user.todos.build(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todos_path, notice: 'Todo was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /todos/1
  def update
    @todo = current_user.todos.find(params[:id])
    if @todo.update(todo_params)
      redirect_to todos_path, notice: 'Todo was successfully updated.'
    else
      render :edit
    end
  end

  def complete
    @todo = current_user.todos.find(params[:id])
    if @todo.done
      @todo.update_attribute(:done, false)
    else
      @todo.update_attribute(:done, true)
    end
    redirect_to todos_path, notice: 'Todo was successfully complete.'
  end

  # DELETE /todos/1
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:done, :description, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BravoTODO</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_back.html.erb
<div class="left-side">
  <%= link_to name = '   ', todos_path, class: "button-back" %>
</div>

app/views/todos/_form-edit.html.erb
<%= form_with(model: todo, local: true) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="main-container-checkbox">
    <div class="checkbox tiny">
      <div class="checkbox-container">
        <%= form.check_box :done, id: "checkbox-tiny", checked_type: "checkbox" %>
        <div class="checkbox-checkmark"></div>
      </div>
      <%= form.label :done, for: "checkbox-tiny" %>
    </div>
  </div>

  <div class="col-1">
    <%= form.text_field :description, class: "effect-1", placeholder: "Description" %>
    <span class="focus-border"></span>
  </div>

  <div class="date-label">
    <%= form.label :date, class: "label" %>
  </div>
  <div class="date">
    <%= form.datetime_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/_form.html.erb
<%= form_with(model: todo, local: true) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-1">
    <%= form.text_field :description, class: "effect-1", placeholder: "Description" %>
    <span class="focus-border"></span>
  </div>

  <div class="date-label">
    <%= form.label :date, class: "label" %>
  </div>
  <div class="date">
    <%= form.datetime_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/_statistic.html.erb
<% @selected_date = Time.current %>
<% @date_last_day = current_user.todos.where('date BETWEEN ? AND ?', 1.day.ago, @selected_date) %>
<% @date_last_week = current_user.todos.where('date BETWEEN ? AND ?', 1.week.ago, @selected_date) %>
<% @date_last_month = current_user.todos.where('date BETWEEN ? AND ?', 1.month.ago, @selected_date) %>
<% @all_time = current_user.todos %>

<p class="enter-h2">Statistic</p>

<table cellpadding="0" cellspacing="0" border="0">
  <tbody>
    <tr>
      <th>Time</th>
      <th>Count complete</th>
      <th>Count not complete</th>
    </tr>
    <tr>
      <td>Per day</td>
      <td>
        <%= @date_last_day.where(done: true).count %>
      </td>
      <td>
        <%= @date_last_day.where(done: false).count %>
      </td>
    </tr>
    <tr>
      <td>Per week</td>
      <td>
        <%= @date_last_week.where(done: true).count %>
      </td>
      <td>
        <%= @date_last_week.where(done: false).count %>
      </td>
    </tr>
    <tr>
      <td>Per month</td>
      <td>
      <%= @date_last_month.where(done: true).count %>
      </td>
      <td>
        <%= @date_last_month.where(done: false).count %>
      </td>
    </tr>
    <tr>
      <td>All</td>
      <td>
        <%= @all_time.where(done: true).count %>
      </td>
      <td>
        <%= @all_time.where(done: false).count %>
      </td>
    </tr>
  </tbody>
</table>

app/views/todos/_user-info.html.erb
<div class="right-side">
  <div>
    <%= image_tag("ico-user-image.png", :alt => "che", style: "float:left") %>
    <p class="user-name" style="float:left"><%= current_user.email %></p>
  </div>
  <br>
  <div>
    <p style="float:left"><%= link_to "    ", destroy_user_session_path, :method => :delete , class: "button-exit"%></p>
    <p style="float:left" class="user-name">Exit</p>
  </div>
</div>

app/views/todos/edit.html.erb
<%= render 'user-info' %>

<div class="enter-div">
  <p class="enter-h2">Editing Todo</p>
  <%= render 'form-edit', todo: @todo %>
</div>

app/views/todos/index.html.erb
<%= render 'user-info' %>

<div class="enter-div">
  <% if notice %>
    <p id="notice"><%= notice %></p>
  <% end %>

  <p class="enter-h2">ToDos</p>

  <div class="col-1">
    <%= link_to '  ', new_todo_path, class: "plus_todo" %>
  </div>

  <div class="tbl-header">
    <table cellpadding="0" cellspacing="0" border="0">
      <thead>
      <tr>
        <th>Done</th>
        <th colspan="3">Description</th>
        <th>Date</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
      </thead>
    </table>
  </div>

  <div class="tbl-content">
    <table  cellpadding="0" cellspacing="0" border="0">
      <tbody>
      <% @todos.each do |todo| %>
        <% if todo.done %>
          <tr class="compete-todo">
        <% else %>
          <tr>
        <% end %>
          <td>
            <% if todo.done %>
              <%= link_to '  ', complete_todo_path(todo), method: :patch, class: "todo-complete" %>
            <% else %>
              <%= link_to '  ', complete_todo_path(todo), method: :patch, class: "todo-uncomplete" %>
            <% end %>
          </td>
          <td colspan="3"><%= todo.description %></td>
          <td><%= todo.date %></td>
          <td><%= link_to '  ', edit_todo_path(todo), class: "todo-edit" %></td>
          <td><%= link_to '  ', todo, method: :delete, data: { confirm: 'Are you sure?' }, class: "delete-todo" %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>

  <%= render 'statistic' %>

</div>

app/views/todos/new.html.erb
<%= render 'user-info' %>

<div class="enter-div">
  <p class="enter-h2">New Todo</p>
  <%= render 'form', todo: @todo %>
</div>

app/views/todos/show.html.erb
<%= render 'user-info' %>
<%= render 'back' %>

<div class="enter-div">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Done:</strong>
    <%= @todo.done %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @todo.description %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= @todo.date %>
  </p>

  <%= link_to 'Edit', edit_todo_path(@todo) %>

</div>

app/views/welcome/index.html.erb
<h1>Welcome to BravoTODO</h1>

<% unless user_signed_in? %>
  <p><%= link_to "Sign up", new_user_registration_path %></p>
  <p><%= link_to "Sign in", new_user_session_path %></p>
<% else %>
  <p><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></p>
<% end %>